spring.application.name=gestion-cursos
# Configuración de conexión a MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/gestion_universidad?useSSL=false&serverTimezone=America/El_Salvador&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Casa2103

# Configuración de JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# Configuración de Thymeleaf
spring.thymeleaf.cache=false

# Puerto del servidor
server.port=8080